/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.culturarte.presentacion;

import com.culturarte.logica.IControlador;
import com.culturarte.logica.datatypes.DTColaboracion;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author fabriciorivero
 */
public class ConsultarColaboraciones extends javax.swing.JInternalFrame {

    private IControlador controlador;
    private DefaultTableModel tabla1;
    private DefaultTableModel tabla3;
    
    /**
     * Creates new form ConsultarColaboraciones
     */
    public ConsultarColaboraciones(IControlador IC) {
        initComponents();
        controlador = IC;
        cargarComboBox();
        tabla1=(DefaultTableModel)jTable1.getModel();
        tabla3=(DefaultTableModel)jTable3.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCcolaboradores = new javax.swing.JComboBox<>();
        jBcerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCcolaboracion = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBselec = new javax.swing.JButton();
        jBselec2 = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Colaboraciones");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jCcolaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcolaboradoresActionPerformed(evt);
            }
        });

        jBcerrar.setText("Cerrar");
        jBcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcerrarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nickname", "Colaboraciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jCcolaboracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCcolaboracionActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Fecha", "Monto", "Tipo de Retorno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setText("Colaboradores");

        jLabel2.setText("Colaboracion");

        jBselec.setText("Seleccionar");
        jBselec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselecActionPerformed(evt);
            }
        });

        jBselec2.setText("Seleccionar");
        jBselec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBselec2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jCcolaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jBselec))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jCcolaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jBselec2)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCcolaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jBselec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCcolaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jBselec2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cargarComboBox();
    }//GEN-LAST:event_formComponentShown

    private void jCcolaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcolaboradoresActionPerformed

    }//GEN-LAST:event_jCcolaboradoresActionPerformed

    private void jCcolaboracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCcolaboracionActionPerformed
        
    }//GEN-LAST:event_jCcolaboracionActionPerformed

    private void jBcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcerrarActionPerformed
        tabla1.setRowCount(0);
        tabla3.setRowCount(0);
        this.jCcolaboradores.removeAllItems();
        this.jCcolaboracion.removeAllItems();
        setVisible(false);
    }//GEN-LAST:event_jBcerrarActionPerformed

    private void jBselecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselecActionPerformed
        String colaboradorSeleccionado = (String) jCcolaboradores.getSelectedItem();
        mostrarColaboraciones(colaboradorSeleccionado);
    }//GEN-LAST:event_jBselecActionPerformed

    private void jBselec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBselec2ActionPerformed
        String colaboracionSeleccionada = (String) jCcolaboracion.getSelectedItem();
        String colaboradorSeleccionado = (String) jCcolaboradores.getSelectedItem();
        mostrarColaboracion(colaboracionSeleccionada,colaboradorSeleccionado);
    }//GEN-LAST:event_jBselec2ActionPerformed

    private void mostrarColaboraciones(String nick){
        ArrayList<DTColaboracion> colaboraciones= controlador.getDTColaboracionesPropuestas(nick);
       
        this.jCcolaboracion.removeAllItems();
        for(DTColaboracion c:colaboraciones){
            tabla1.setRowCount(0);
            Object[] fila = {nick, c.getPropuestaTitulo().trim()};
            tabla1.addRow(fila);
            this.jCcolaboracion.addItem(c.getPropuestaTitulo());
        }
    }
    
    private void mostrarColaboracion(String colab,String nick){
        DTColaboracion c= controlador.getDTColaboracionPropuesta(nick,colab);
       
        tabla3.setRowCount(0);
        if(c!=null){
            Object[] fila = {c.getFecha(),c.getMonto(),c.getTipoRetorno()};
            tabla3.addRow(fila);
        }
    }
    
    private void cargarComboBox() {
        this.jCcolaboradores.removeAllItems();
        this.jCcolaboracion.removeAllItems();
        
        ArrayList<String> nomColab = controlador.getNickColaboradores();
        for (String p : nomColab) {
            this.jCcolaboradores.addItem(p);
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcerrar;
    private javax.swing.JButton jBselec;
    private javax.swing.JButton jBselec2;
    private javax.swing.JComboBox<String> jCcolaboracion;
    private javax.swing.JComboBox<String> jCcolaboradores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
