/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.culturarte.presentacion;

import com.culturarte.logica.IControlador;
import com.culturarte.logica.datatypes.DTPropuesta;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabriciorivero
 */
public class ConsultarPropuestas extends javax.swing.JInternalFrame {

    private IControlador controlador;
    /**
     * Creates new form ConsultarPropuestas
     */
    public ConsultarPropuestas(IControlador IC) {
        initComponents();
        controlador = IC;
        cargarLista();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaPropuesta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        jlLugar = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jlPrecio = new javax.swing.JLabel();
        jlMontoRec = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlColaboradores = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jlMontoNec = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDesc = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Propuestas");

        listaPropuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPropuestaActionPerformed(evt);
            }
        });

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlTitulo.setText("jLabel2");

        jlLugar.setText("jLabel2");

        jlFecha.setText("jLabel2");

        jlPrecio.setText("jLabel2");

        jlMontoRec.setText("jLabel2");

        jlColaboradores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlColaboradores);

        jLabel2.setText("Colaboradores:");

        jlMontoNec.setText("jLabel3");

        jScrollPane2.setViewportView(jtaDesc);

        jLabel3.setText("Precio:");

        jLabel4.setText("Monto Recaudado:");

        jLabel5.setText("Monto Necesario:");

        jLabel6.setText("Titulo:");

        jLabel7.setText("Lugar:");

        jLabel8.setText("Fecha:");

        jLabel9.setText("Descripcion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listaPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlLugar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlTitulo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMontoRec)
                            .addComponent(jlMontoNec)
                            .addComponent(jlPrecio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listaPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlTitulo)
                                    .addComponent(jlPrecio)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlLugar)
                                            .addComponent(jlMontoRec)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlFecha)
                                            .addComponent(jlMontoNec)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaPropuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPropuestaActionPerformed
        String propuestaSeleccionada=(String)listaPropuesta.getSelectedItem();
        if(propuestaSeleccionada!=null){
            mostrarInfoPropuesta(propuestaSeleccionada);
        }
    }//GEN-LAST:event_listaPropuestaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       cargarLista();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void mostrarInfoPropuesta(String propuesta){
        DTPropuesta p = controlador.getDTPropuesta(propuesta);
        ArrayList<String> nomColab = p.getNomColaboradores();
        
        String colaboradores = nomColab.isEmpty() ? "Sin Colaboradores" : String.join(", ", nomColab);
        jlTitulo.setText(p.getTitulo());
        jtaDesc.setText(p.getDescripcion());
        jlLugar.setText(p.getLugar());
        jlFecha.setText(p.getFechaPrevista().toString());
        jlPrecio.setText(String.valueOf(p.getPrecioEntrada()));
        jlMontoRec.setText(String.valueOf(p.getMontoRecaudado()));
        jlMontoNec.setText(String.valueOf(p.getMontoNecesario()));
        DefaultListModel dlm = new DefaultListModel();
        dlm.clear();
        dlm.addElement(colaboradores);
        jlColaboradores.setModel(dlm);
        
        
       File imagenFile = p.getImagen();
        
        if (imagenFile != null && imagenFile.exists()) {
            ImageIcon icon = new ImageIcon(imagenFile.getAbsolutePath());
           //escala la imagen al tamaño del JLabel
            Image imagenEscalada = icon.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(imagenEscalada));
        }   
        else {
            jLabel1.setIcon(null); // limpia si no hay imagen
        }
    }
    
    private void cargarLista() {
        ArrayList<String> propuestas = controlador.getTituloPropuestas();

        this.listaPropuesta.removeAllItems(); // limpia cualquier elemento previo

        for (String p : propuestas) {
            this.listaPropuesta.addItem(p); // agregamos solo el titulo
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlColaboradores;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlLugar;
    private javax.swing.JLabel jlMontoNec;
    private javax.swing.JLabel jlMontoRec;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextPane jtaDesc;
    private javax.swing.JComboBox<String> listaPropuesta;
    // End of variables declaration//GEN-END:variables
}
