/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.culturarte.presentacion;

import com.culturarte.logica.IControlador;
import com.culturarte.logica.datatypes.DTEstado;
import com.culturarte.logica.datatypes.DTPropuesta;
import com.culturarte.logica.enums.TipoEstado;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabriciorivero
 */
public class ConsultarPropuestasPorEstado extends javax.swing.JInternalFrame {

    private IControlador controlador;
    /**
     * Creates new form ConsultarPropuestasPorEstado
     */
    public ConsultarPropuestasPorEstado(IControlador IC) {
        initComponents();
        controlador = IC;
        //Cargo ComboBox de Propuestas por TipoEstado 
        comboEstadoProp.removeAllItems();
        for (TipoEstado e : TipoEstado.values()) {
            comboEstadoProp.addItem(e.toString());
        }
        listaPropuestas.addListSelectionListener(e->{
        if(!e.getValueIsAdjusting()){
                if(listaPropuestas.getSelectedValue() != null){
                    cargarTabla();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEstadoProp = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPropuestas = new javax.swing.JList<>();
        fotoPropuesta = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaDesc = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlLugar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlPrecio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlMontoRec = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlColaboradores = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlProponente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlMontoNec = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaEstados = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jlCategoria = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar propuestas por estado");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        comboEstadoProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoPropActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaPropuestas);

        jtaDesc.setEditable(false);
        jScrollPane3.setViewportView(jtaDesc);

        jLabel10.setText("Hist. Estados:");

        jlTitulo.setText("jLabel2");

        jLabel3.setText("Precio Entrada:");

        jlLugar.setText("jLabel2");

        jLabel4.setText("Monto Recaudado:");

        jlFecha.setText("jLabel2");

        jLabel5.setText("Monto Necesario:");

        jlPrecio.setText("jLabel2");

        jLabel6.setText("Titulo:");

        jlMontoRec.setText("jLabel2");

        jLabel7.setText("Lugar:");

        jlColaboradores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlColaboradores);

        jLabel8.setText("Fecha:");

        jLabel11.setText("Proponente: ");

        jLabel9.setText("Descripcion:");

        jlProponente.setText("jLabel2");

        jLabel2.setText("Colaboradores:");

        jlMontoNec.setText("jLabel3");

        tablaEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Estado", "Fecha", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEstados.setEnabled(false);
        jScrollPane5.setViewportView(tablaEstados);

        jLabel12.setText("Categoria:");

        jlCategoria.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboEstadoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlLugar)
                                    .addComponent(jlFecha)
                                    .addComponent(jlTitulo))))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCategoria)
                    .addComponent(jlMontoNec)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMontoRec)
                    .addComponent(jlPrecio)
                    .addComponent(jlProponente))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fotoPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(comboEstadoProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlTitulo)
                                        .addComponent(jLabel11))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlLugar)
                                            .addGap(18, 18, 18)
                                            .addComponent(jlFecha))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel5)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jlCategoria)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlProponente)
                                    .addGap(18, 18, 18)
                                    .addComponent(jlPrecio)
                                    .addGap(18, 18, 18)
                                    .addComponent(jlMontoRec)
                                    .addGap(18, 18, 18)
                                    .addComponent(jlMontoNec)))
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEstadoPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoPropActionPerformed
        cargarCombo();
    }//GEN-LAST:event_comboEstadoPropActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cargarCombo();
    }//GEN-LAST:event_formComponentShown

    private void cargarCombo(){       
        DefaultListModel dlm = new DefaultListModel<>();
        String seleccionado = (String) comboEstadoProp.getSelectedItem();
        TipoEstado estado = TipoEstado.valueOf(seleccionado);
        for(String s : controlador.getTituloPropuestasPorEstado(estado)){
            dlm.addElement(s);
        }
        listaPropuestas.setModel(dlm);
       
    if (fotoPropuesta != null) {
        fotoPropuesta.setIcon(null);
    }
    }
    
    private void cargarTabla(){   
        DTPropuesta p = controlador.getDTPropuesta(listaPropuestas.getSelectedValue());
        ArrayList<String> nomColab = p.getNomColaboradores();
        
        jlTitulo.setText(p.getTitulo());
        jtaDesc.setText(p.getDescripcion());
        jlLugar.setText(p.getLugar());
        jlFecha.setText(p.getFechaPrevista().toString());
        jlPrecio.setText(String.valueOf(p.getPrecioEntrada()));
        jlMontoRec.setText(String.valueOf(p.getMontoRecaudado()));
        jlMontoNec.setText(String.valueOf(p.getMontoNecesario()));
        jlProponente.setText(p.getProponente());
        jlCategoria.setText(p.getCategoria());
        
        // Lista colaboradores
        DefaultListModel dlm = new DefaultListModel();
        dlm.clear();
        if (nomColab.isEmpty()) {
            dlm.addElement("Sin colaboradores");
        } else {
            for (String colab : nomColab) {
                dlm.addElement(colab);
            }
        }
        jlColaboradores.setModel(dlm);
        
        // Historial Estados
        
        DefaultTableModel dtm = new DefaultTableModel(new String[]{"Estado", "Fecha", "Hora"}, 0);
        for (DTEstado e : p.getHistEstados()) {
            dtm.addRow(new String[]{e.getEstado(),e.getFecha(),e.getHora()});
        }
        tablaEstados.setModel(dtm);
        
        // Imagen

       File imagenFile = p.getImagen();
        
        if (imagenFile != null && imagenFile.exists()) {
            ImageIcon icon = new ImageIcon(imagenFile.getAbsolutePath());
           //escala la imagen al tamaño del JLabel
            Image imagenEscalada = icon.getImage().getScaledInstance(fotoPropuesta.getWidth(),fotoPropuesta.getHeight(),Image.SCALE_SMOOTH);
            fotoPropuesta.setIcon(new ImageIcon(imagenEscalada));
        }   
        else {
            fotoPropuesta.setIcon(null); // limpia si no hay imagen
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEstadoProp;
    private javax.swing.JLabel fotoPropuesta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JList<String> jlColaboradores;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlLugar;
    private javax.swing.JLabel jlMontoNec;
    private javax.swing.JLabel jlMontoRec;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JLabel jlProponente;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextPane jtaDesc;
    private javax.swing.JList<String> listaPropuestas;
    private javax.swing.JTable tablaEstados;
    // End of variables declaration//GEN-END:variables
}
