/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.culturarte.presentacion;

import com.culturarte.logica.IControlador;
import com.culturarte.logica.datatypes.DTProponente;
import com.culturarte.logica.datatypes.DTPropuesta;
import com.culturarte.logica.enums.TipoEstado;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabriciorivero
 */
public class ConsultarProponente extends javax.swing.JInternalFrame {

    private IControlador controlador;
    
    public ConsultarProponente(IControlador controlador) {
        initComponents(); 
        this.controlador = controlador;
        
        //ComboBox de Proponentes
        cargarComboBox(); 
        
        jTextField1.setEditable(false);
        jTable1.setTableHeader(null);
        
        //ComboBox de Propuestas por TipoEstado 
        comboEstadoProp.removeAllItems();
        for (TipoEstado e : TipoEstado.values()) {
            comboEstadoProp.addItem(e.toString());
        }
        
        jTable2.getSelectionModel().addListSelectionListener(e-> {
            if(!e.getValueIsAdjusting()){
                mostrarColaboradores();
            }
        });
       
    }
       

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaProponentes = new javax.swing.JComboBox<>();
        btnCargar = new javax.swing.JButton();
        comboEstadoProp = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlColab = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Proponente");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        ListaProponentes.setName("comboProponentes"); // NOI18N
        ListaProponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaProponentesActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        comboEstadoProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoPropActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Monto Recaudado", "Monto Necesario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jLabel2.setText("Propuestas:");
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 14))); // NOI18N

        jScrollPane3.setViewportView(jlColab);

        jTextField1.setText("Colaboradores");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ListaProponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCargar))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboEstadoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListaProponentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEstadoProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaProponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaProponentesActionPerformed
        String proponenteSeleccionado = (String) ListaProponentes.getSelectedItem();
        if(proponenteSeleccionado != null){
            mostrarInfoProponente(proponenteSeleccionado);
        
            DTProponente p = controlador.getDTProponente(proponenteSeleccionado);
            mostrarPropuestas(p);
        
       
        } 
       
    }//GEN-LAST:event_ListaProponentesActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cargarComboBox();
    }//GEN-LAST:event_formComponentShown

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        cargarComboBox();
        
    }//GEN-LAST:event_btnCargarActionPerformed

    private void comboEstadoPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoPropActionPerformed
        String proponente = (String) ListaProponentes.getSelectedItem();
        if(proponente != null){
            DTProponente p = controlador.getDTProponente(proponente);
            mostrarPropuestas(p);
        }
    }//GEN-LAST:event_comboEstadoPropActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String proponente = (String) ListaProponentes.getSelectedItem();
        if(proponente != null){
            DTProponente p = controlador.getDTProponente(proponente);
            mostrarPropuestas(p);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
        
    private void mostrarPropuestas(DTProponente proponente){
        
        String estado = (String) comboEstadoProp.getSelectedItem();
        if(estado == null) {
            return;
        }
        TipoEstado estadoElegido = TipoEstado.valueOf(estado);
        DefaultTableModel dtm = new DefaultTableModel(new Object[]{"Titulo", "Monto Recaudado", "Monto Necesario"},0);
        jTable2.setDefaultEditor(Object.class, null); 
        //Constructor
        for (DTPropuesta p : proponente.getPropuestas()){
            if(p.getEstadoActual() == estadoElegido){
                Object [] filas = {
                    p.getTitulo(),
                    p.getMontoRecaudado(),
                    p.getMontoNecesario()
                };
                 dtm.addRow(filas);
            }
            
        }
        jTable2.setModel(dtm);
        
    }
    
    private void mostrarColaboradores(){
        int filaSelec = jTable2.getSelectedRow();
        if(filaSelec >= 0){
            String tituloProp = (String) jTable2.getValueAt(filaSelec, 0);
            DTPropuesta propuesta = controlador.getDTPropuesta(tituloProp);
            
            ArrayList<String> nomColab = propuesta.getNomColaboradores();
            
            DefaultListModel dlm = new DefaultListModel();
            if(nomColab.isEmpty()){
                dlm.addElement("Sin Colaboradores");
            }else{
                for(String n : nomColab){
                    dlm.addElement(n);
                }
            }
            jlColab.setModel(dlm);
        }
    }
    
    private void mostrarInfoProponente(String nickname){
        
        DTProponente p = controlador.getDTProponente(nickname); // Acá ya tenemos toda la info para mostrar ...
        
        // TODO : Añadir info al gui 
        Object[][] data = { 
            {"Nickname", p.getNickname()}, 
            {"Nombre", p.getNombre()}, 
            {"Apellido", p.getApellido()}, 
            {"Fecha nacimiento", p.getFechaNacimiento()}, 
            {"Correo electronico", p.getEmail()},
            {"Direccion", p.getDireccion()},
            {"Biografia", p.getBiografia()},
            {"Link Web", p.getLinkWeb()}
        }; 
        
        DefaultTableModel dtm = new DefaultTableModel(data, new String[]{"", ""}); 
        jTable1.setDefaultEditor(Object.class, null); 
        jTable1.setModel(dtm);
        
        File imagenFile = p.getImagen();
        
        if (imagenFile != null && imagenFile.exists()) {
            ImageIcon icon = new ImageIcon(imagenFile.getAbsolutePath());
           //escala la imagen al tamaño del JLabel
            Image imagenEscalada = icon.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(imagenEscalada));
        }   
        else {
            jLabel1.setIcon(null); // limpia si no hay imagen
        }
    }
    
    
    
    private void cargarComboBox() {
        ArrayList<String> nomProponentes = controlador.getNomProponentes();

        this.ListaProponentes.removeAllItems(); // limpia cualquier elemento previo

        for (String p : nomProponentes) {
            this.ListaProponentes.addItem(p); // agregamos solo el nickname
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListaProponentes;
    private javax.swing.JButton btnCargar;
    private javax.swing.JComboBox<String> comboEstadoProp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> jlColab;
    // End of variables declaration//GEN-END:variables
}
