/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.culturarte.presentacion;

import com.culturarte.logica.IControlador;
import com.culturarte.logica.datatypes.DTProponente;
import com.culturarte.logica.datatypes.DTPropuesta;
import com.culturarte.logica.enums.TipoEstado;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabriciorivero
 */
public class ConsultarProponente extends javax.swing.JInternalFrame {

    private IControlador controlador;
    
    
    public ConsultarProponente(IControlador controlador) {
        initComponents(); 
        this.controlador = controlador;
        
        //ComboBox de Proponentes
        cargarComboBox(); 
        
        
        jTable1.setTableHeader(null);
        
        //ComboBox de Propuestas por TipoEstado 
        comboEstadoProp.removeAllItems();
        for (TipoEstado e : TipoEstado.values()) {
            comboEstadoProp.addItem(e.toString());
        }
        
       
    }
       

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaProponentes = new javax.swing.JComboBox<>();
        btnCargar = new javax.swing.JButton();
        comboEstadoProp = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Proponente");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        ListaProponentes.setName("comboProponentes"); // NOI18N
        ListaProponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaProponentesActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        comboEstadoProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoPropActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Colaboradores", "Monto Recaudado", "Monto Necesario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ListaProponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCargar))
                            .addComponent(comboEstadoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListaProponentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(comboEstadoProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaProponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaProponentesActionPerformed
        String proponenteSeleccionado = (String) ListaProponentes.getSelectedItem();
        if(proponenteSeleccionado != null)
            mostrarInfoProponente(proponenteSeleccionado);
    }//GEN-LAST:event_ListaProponentesActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cargarComboBox();
    }//GEN-LAST:event_formComponentShown

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        cargarComboBox();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void comboEstadoPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoPropActionPerformed
        String proponente = (String) ListaProponentes.getSelectedItem();
        if(proponente != null){
            DTProponente p = controlador.getDTProponente(proponente);
            mostrarPropuestas(p);
        }
    }//GEN-LAST:event_comboEstadoPropActionPerformed
        
    private void mostrarPropuestas(DTProponente proponente){
        String estado = (String) comboEstadoProp.getSelectedItem();
        TipoEstado estadoElegido = TipoEstado.valueOf(estado);
        DefaultTableModel dtm = new DefaultTableModel();
        
        //Constructor
        for (DTPropuesta p : proponente.getPropuestas()){
            if(p.getEstadoActual() == estadoElegido){
                ArrayList<String> nomColaboradores = p.getNomColaboradores();
                String colaboradores = nomColaboradores.isEmpty() ? "Sin Colaboradores" : String.join(", ", nomColaboradores);
                Object [] filas = {
                    p.getTitulo(),
                    colaboradores,
                    p.getMontoRecaudado(),
                    p.getMontoNecesario()
                };
                 dtm.addRow(filas);
            }
            
        }
        jTable2.setModel(dtm);
        
    }
    
    private void mostrarInfoProponente(String nickname){
        
        DTProponente p = controlador.getDTProponente(nickname); // Acá ya tenemos toda la info para mostrar ...
        
        // TODO : Añadir info al gui 
        Object[][] data = { 
            {"Nickname", p.getNickname()}, 
            {"Nombre", p.getNombre()}, 
            {"Apellido", p.getApellido()}, 
            {"Fecha nacimiento", p.getFechaNacimiento()}, 
            {"Correo electronico", p.getEmail()},
            {"Link Web", p.getLinkWeb()}
        }; 
        
        DefaultTableModel dtm = new DefaultTableModel(data, new String[]{"", ""}); 
        jTable1.setDefaultEditor(Object.class, null); 
        jTable1.setModel(dtm);
        
        if(p.getImagen() != null){
            ImageIcon foto = new ImageIcon(p.getImagen().getAbsolutePath());
        
        Image img = foto.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        jLabel1.setIcon(new ImageIcon(img));
        }else{
            //Ver de poner una imagen por defecto
            jLabel1.setIcon(null);
        }
        
        
    }
    
    
    
    private void cargarComboBox() {
        ArrayList<String> nomProponentes = controlador.getNomProponentes();

        this.ListaProponentes.removeAllItems(); // limpia cualquier elemento previo

        for (String p : nomProponentes) {
            this.ListaProponentes.addItem(p); // agregamos solo el nickname
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListaProponentes;
    private javax.swing.JButton btnCargar;
    private javax.swing.JComboBox<String> comboEstadoProp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
