/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.culturarte.presentacion;

import com.culturarte.logica.IControlador;
import com.culturarte.logica.datatypes.DTPropuesta;
import com.culturarte.logica.enums.TipoEstado;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabriciorivero
 */
public class ConsultarPropuestasPorEstado extends javax.swing.JInternalFrame {

    private IControlador controlador;
    private DefaultTableModel dtm;
    /**
     * Creates new form ConsultarPropuestasPorEstado
     */
    public ConsultarPropuestasPorEstado(IControlador IC) {
        initComponents();
        controlador = IC;
        //Cargo ComboBox de Propuestas por TipoEstado 
        comboEstadoProp.removeAllItems();
        for (TipoEstado e : TipoEstado.values()) {
            comboEstadoProp.addItem(e.toString());
        }
        dtm = new DefaultTableModel();
        dtm.addColumn("Título");
        dtm.addColumn("Colaboradores");
        dtm.addColumn("Lugar");
        dtm.addColumn("Precio Entrada");
        dtm.addColumn("Monto Recaudado");
        tablaDatosPropuesta.setModel(dtm);
        listaPropuestas.addListSelectionListener(e->{
        if(!e.getValueIsAdjusting()){
                if(listaPropuestas.getSelectedValue() != null){
                    cargarTabla();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEstadoProp = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPropuestas = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatosPropuesta = new javax.swing.JTable();
        fotoPropuesta = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar propuestas por estado");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        comboEstadoProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoPropActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaPropuestas);

        tablaDatosPropuesta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Colaboradores", "Lugar", "Precio Entrada", "Monto Recaudado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDatosPropuesta);

        fotoPropuesta.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fotoPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(comboEstadoProp, 0, 120, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboEstadoProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(fotoPropuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEstadoPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoPropActionPerformed
        cargarCombo();
    }//GEN-LAST:event_comboEstadoPropActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cargarCombo();
    }//GEN-LAST:event_formComponentShown

    private void cargarCombo(){
        DefaultListModel dlm = new DefaultListModel<>();
        String seleccionado = (String) comboEstadoProp.getSelectedItem();
        TipoEstado estado = TipoEstado.valueOf(seleccionado);
        for(String s : controlador.getTituloPropuestasPorEstado(estado)){
            dlm.addElement(s);
        }
        listaPropuestas.setModel(dlm);
    }
    
    private void cargarTabla(){       
        DTPropuesta p = controlador.getDTPropuesta(listaPropuestas.getSelectedValue());
        ArrayList<String> nomColaboradores = p.getNomColaboradores();
        String colaboradores = nomColaboradores.isEmpty() ? "Sin Colaboradores" : String.join(", ", nomColaboradores);
        Object[] data = {
            p.getTitulo(), colaboradores, p.getLugar(), p.getPrecioEntrada(), p.getMontoRecaudado()
        };
        dtm.addRow(data);
        tablaDatosPropuesta.setModel(dtm); 
        tablaDatosPropuesta.setDefaultEditor(Object.class, null); 
        //Corregir el ancho de las columnas
        tablaDatosPropuesta.getColumnModel().getColumn(0).setPreferredWidth(150);
        tablaDatosPropuesta.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaDatosPropuesta.getColumnModel().getColumn(2).setPreferredWidth(130);
        tablaDatosPropuesta.getColumnModel().getColumn(3).setPreferredWidth(100);
        tablaDatosPropuesta.getColumnModel().getColumn(4).setPreferredWidth(100);

        
        if(p.getImagen() != null){
            ImageIcon foto = new ImageIcon(p.getImagen().getAbsolutePath());
            Image img = foto.getImage().getScaledInstance(fotoPropuesta.getWidth(), fotoPropuesta.getHeight(), Image.SCALE_SMOOTH);
            fotoPropuesta.setIcon(new ImageIcon(img));
        }else{
            fotoPropuesta.setIcon(null);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEstadoProp;
    private javax.swing.JLabel fotoPropuesta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaPropuestas;
    private javax.swing.JTable tablaDatosPropuesta;
    // End of variables declaration//GEN-END:variables
}
