/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.culturarte.presentacion;

import com.culturarte.logica.IControlador;
import com.culturarte.logica.datatypes.DTPropuesta;
import com.culturarte.logica.enums.TipoEstado;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabriciorivero
 */
public class ConsultarPropuestasPorEstado extends javax.swing.JInternalFrame {

    private IControlador controlador;
    /**
     * Creates new form ConsultarPropuestasPorEstado
     */
    public ConsultarPropuestasPorEstado(IControlador IC) {
        initComponents();
        controlador = IC;
        //Cargo ComboBox de Propuestas por TipoEstado 
        comboEstadoProp.removeAllItems();
        for (TipoEstado e : TipoEstado.values()) {
            comboEstadoProp.addItem(e.toString());
        }
        listaPropuestas.addListSelectionListener(e->{
        if(!e.getValueIsAdjusting()){
                if(listaPropuestas.getSelectedValue() != null){
                    cargarTabla();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEstadoProp = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPropuestas = new javax.swing.JList<>();
        fotoPropuesta = new javax.swing.JLabel();
        jlLugar = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jlPrecio = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jlMontoRec = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlColaboradores = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlMontoNec = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaDesc = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar propuestas por estado");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        comboEstadoProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoPropActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaPropuestas);

        jlLugar.setText("jLabel2");

        jlFecha.setText("jLabel2");

        jlPrecio.setText("jLabel2");

        jlTitulo.setText("jLabel2");

        jlMontoRec.setText("jLabel2");

        jLabel5.setText("Monto Necesario:");

        jLabel6.setText("Titulo:");

        jlColaboradores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlColaboradores);

        jLabel7.setText("Lugar:");

        jLabel2.setText("Colaboradores:");

        jlMontoNec.setText("jLabel3");

        jLabel8.setText("Fecha:");

        jLabel9.setText("Descripcion:");

        jScrollPane3.setViewportView(jtaDesc);

        jLabel3.setText("Precio:");

        jLabel4.setText("Monto Recaudado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboEstadoProp, 0, 165, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fotoPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlFecha))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlLugar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMontoRec)
                    .addComponent(jlMontoNec)
                    .addComponent(jlPrecio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlTitulo)
                                    .addComponent(jlPrecio)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlLugar)
                                            .addComponent(jlMontoRec)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlFecha)
                                            .addComponent(jlMontoNec)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(fotoPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboEstadoProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(339, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEstadoPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoPropActionPerformed
        cargarCombo();
    }//GEN-LAST:event_comboEstadoPropActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cargarCombo();
    }//GEN-LAST:event_formComponentShown

    private void cargarCombo(){       
        DefaultListModel dlm = new DefaultListModel<>();
        String seleccionado = (String) comboEstadoProp.getSelectedItem();
        TipoEstado estado = TipoEstado.valueOf(seleccionado);
        for(String s : controlador.getTituloPropuestasPorEstado(estado)){
            dlm.addElement(s);
        }
        listaPropuestas.setModel(dlm);
       
    if (fotoPropuesta != null) {
        fotoPropuesta.setIcon(null);
    }
    }
    
    private void cargarTabla(){   
        DTPropuesta p = controlador.getDTPropuesta(listaPropuestas.getSelectedValue());
        ArrayList<String> nomColaboradores = p.getNomColaboradores();
        String colaboradores = nomColaboradores.isEmpty() ? "Sin Colaboradores" : String.join(", ", nomColaboradores);
       
        jlTitulo.setText(p.getTitulo());
        jtaDesc.setText(p.getDescripcion());
        jlLugar.setText(p.getLugar());
        jlFecha.setText(p.getFechaPrevista().toString());
        jlPrecio.setText(String.valueOf(p.getPrecioEntrada()));
        jlMontoRec.setText(String.valueOf(p.getMontoRecaudado()));
        jlMontoNec.setText(String.valueOf(p.getMontoNecesario()));
        DefaultListModel dlm = new DefaultListModel();
        dlm.clear();
        dlm.addElement(colaboradores);
        jlColaboradores.setModel(dlm);

        if(p.getImagen() != null){
            ImageIcon foto = new ImageIcon(p.getImagen().getAbsolutePath());
            Image img = foto.getImage().getScaledInstance(fotoPropuesta.getWidth(), fotoPropuesta.getHeight(), Image.SCALE_SMOOTH);
            fotoPropuesta.setIcon(new ImageIcon(img));
        }else{
            fotoPropuesta.setIcon(null);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEstadoProp;
    private javax.swing.JLabel fotoPropuesta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> jlColaboradores;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlLugar;
    private javax.swing.JLabel jlMontoNec;
    private javax.swing.JLabel jlMontoRec;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextPane jtaDesc;
    private javax.swing.JList<String> listaPropuestas;
    // End of variables declaration//GEN-END:variables
}
