/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.culturarte.presentacion;

import com.culturarte.logica.IControlador;
import com.culturarte.logica.clases.Propuesta;
import com.culturarte.logica.datatypes.DTPropuesta;
import com.culturarte.logica.manejadores.ManejadorPropuesta;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.Image;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabriciorivero
 */
public class ModificarPropuesta extends javax.swing.JInternalFrame {

    private IControlador controlador;
    
    /**
     * Creates new form ModificarPropuesta
     */
    public ModificarPropuesta(IControlador IC) {
        initComponents();
        controlador = IC;
        //Cargo combobox
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboPropuestas = new javax.swing.JComboBox<>();
        imagenPropuesta = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificar Propuesta");

        comboPropuestas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPropuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPropuestasActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        bntCancelar.setText("Aceptar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCargar)))
                .addContainerGap(356, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(imagenPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(bntCancelar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPropuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPropuestasActionPerformed
        mostrarDatosPropuesta();
    }//GEN-LAST:event_comboPropuestasActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String propuestaSeleccionada = (String) comboPropuestas.getSelectedItem();
        if(propuestaSeleccionada == null){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una propuesta primero");
            return;
        }
        
        Propuesta p = ManejadorPropuesta.getInstancia().getPropuesta(propuestaSeleccionada);
        
        JDialog dialog = new JDialog((Frame) null, "Modificar Datos", true);
        JLabel lbl1 = new JLabel("Campo a modificar");
        String [] campos = {"Titulo", "Descripcion", "Lugar", "Fecha Prevista", "Precio Entrada", "Monto Necesario"}; 
        JComboBox<String> comboCampos = new JComboBox<>(campos);
        
        JLabel lbl2 = new JLabel("Valores a modificar");
        JTextField txt = new JTextField(15);
        
        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.addActionListener(e-> {
        String campoSeleccionado = (String) comboCampos.getSelectedItem();
        String cambio = txt.getText().trim();
        if(cambio.isEmpty()){
            JOptionPane.showMessageDialog(dialog, "Debe ingresar un valor");
            return;
        }
        try{
        switch(campoSeleccionado){
            case "Titulo":
                break;
            case "Descripcion":
                p.setDescripcion(cambio);
                break;
            case "Lugar":
                p.setLugar(cambio);
                break;
            case "Fecha Prevista":
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/mm/yyyy");
                LocalDate fecha = LocalDate.parse(cambio, formatter);
                p.setFechaPrevista(fecha);
                break;
            case "Precio Entrada":
                float precio = Float.parseFloat(cambio);
                p.setPrecioEntrada(precio);
                break;
            case "Monto Necesario":
                float monto = Float.parseFloat(cambio);
                p.setMontoNecesario(monto);
                break;
            }
        JOptionPane.showMessageDialog(dialog, "Cambio realizado con exito");
        dialog.dispose();
        }catch(NumberFormatException exNum){
            JOptionPane.showMessageDialog(dialog, "Debe ingresar un numero valido");
        }catch(DateTimeParseException exFecha){
            JOptionPane.showMessageDialog(dialog, "Debe ingresar una fecha valida, formato(dd/mm/yyyy)");
            }
        });
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(3,2,10,10));
        panel.add(lbl1);
        panel.add(comboCampos);
         panel.add(lbl2);
    panel.add(txt);
    panel.add(new JLabel());
    panel.add(btnAceptar);

    dialog.add(panel);
    dialog.pack();
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        cargarComboBox();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void cargarComboBox(){
        ArrayList<String> tituloPropuestas = controlador.getTituloPropuestas();
        this.comboPropuestas.removeAllItems();
        for (String t : tituloPropuestas) {
            this.comboPropuestas.addItem(t);//Agrego solo el titulo
        }
    }
    
    private void mostrarDatosPropuesta(){
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JComboBox<String> comboPropuestas;
    private javax.swing.JLabel imagenPropuesta;
    // End of variables declaration//GEN-END:variables
}
