package com.culturarte.presentacion;

import com.culturarte.exepciones.ColaboracionYaExiste;
import com.culturarte.logica.IControlador;
import com.culturarte.logica.datatypes.DTPropuesta;
import com.culturarte.logica.enums.TipoRetorno;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class RegistrarColaboraciones extends javax.swing.JInternalFrame {

    private IControlador controlador;
    
    public RegistrarColaboraciones(IControlador IC) {
        initComponents();
        controlador = IC;
        cargarCombo();
        cargarLista();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlPropuesta = new javax.swing.JLabel();
        comboPropuestas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlMontoColab = new javax.swing.JLabel();
        jtMontoColaboracion = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboColaboradores = new javax.swing.JComboBox<>();
        jlTipoRet = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTipoRet = new javax.swing.JList<>();
        btnAceptar = new javax.swing.JButton();
        jlPrecio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlMontoRec = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlMontoNec = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDesc = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlProponente = new javax.swing.JLabel();
        jlLugar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlEstadoActual = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar colaboraciones");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setName(""); // NOI18N
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jlPropuesta.setText("Propuesta");

        comboPropuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPropuestasActionPerformed(evt);
            }
        });

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Para hacer Colaboracion, ingrese los siguientes datos:");

        jlMontoColab.setText("Monto Colaboracion");

        jtMontoColaboracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMontoColaboracionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setText("Colaborador");

        comboColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColaboradoresActionPerformed(evt);
            }
        });

        jlTipoRet.setText("Tipo de Retorno");

        jScrollPane1.setViewportView(listaTipoRet);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jlPrecio.setText("jLabel2");

        jLabel6.setText("Titulo:");

        jlMontoRec.setText("jLabel2");

        jLabel7.setText("Lugar:");

        jLabel8.setText("Fecha:");

        jLabel9.setText("Descripcion:");

        jlMontoNec.setText("jLabel3");

        jtaDesc.setEditable(false);
        jScrollPane2.setViewportView(jtaDesc);

        jLabel12.setText("Proponente: ");

        jlTitulo.setText("jLabel2");

        jLabel13.setText("Precio Entrada:");

        jlProponente.setText("jLabel2");

        jlLugar.setText("jLabel2");

        jLabel4.setText("Monto Recaudado:");

        jlFecha.setText("jLabel2");

        jLabel5.setText("Monto Necesario:");

        jLabel10.setText("Estado actual:");

        jlEstadoActual.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlLugar)
                                    .addComponent(jlFecha)
                                    .addComponent(jlTitulo))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlMontoNec)
                                    .addComponent(jlMontoRec)
                                    .addComponent(jlPrecio)
                                    .addComponent(jlProponente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jlEstadoActual)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jlMontoColab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtMontoColaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(105, 105, 105)
                                .addComponent(comboColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jlTipoRet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAceptar)
                                        .addGap(56, 56, 56)
                                        .addComponent(btnCancelar))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(59, 59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPropuesta)
                    .addComponent(comboPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(86, 86, 86))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTitulo)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(jlEstadoActual)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlLugar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlFecha)
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlProponente)
                                .addGap(18, 18, 18)
                                .addComponent(jlPrecio)
                                .addGap(18, 18, 18)
                                .addComponent(jlMontoRec)
                                .addGap(18, 18, 18)
                                .addComponent(jlMontoNec)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMontoColab)
                    .addComponent(jtMontoColaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlTipoRet)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnAceptar))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cargarCombo();
    }//GEN-LAST:event_formComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        cargarCombo();
    }//GEN-LAST:event_jPanel1ComponentShown

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String titulo = (String) comboPropuestas.getSelectedItem();
        String tipoRetornoStr = (String) listaTipoRet.getSelectedValue();
        TipoRetorno tipoRetorno = TipoRetorno.valueOf(tipoRetornoStr);
        String montoC = jtMontoColaboracion.getText().trim();
        float montoColaboracion = 0;
        try{
            montoColaboracion = Float.parseFloat(montoC);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El monto no puede ser texto", "ERROR", JOptionPane.ERROR_MESSAGE);

            return;
        }

        String nick = (String) comboColaboradores.getSelectedItem();
        if (nick == null || nick.isBlank()) {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar un colaborador válido",
                "Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try{
            controlador.altaColaboracion(montoColaboracion, LocalDate.now(), LocalTime.now(), tipoRetorno, titulo, nick);
        }catch(ColaboracionYaExiste e){
            JOptionPane.showMessageDialog(this, "La colaboracion ya existe" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Colaboracion registrada correctamente." + titulo + " " + nick);
        btnCancelarActionPerformed(evt);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void comboColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColaboradoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboColaboradoresActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.jtMontoColaboracion.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtMontoColaboracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMontoColaboracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMontoColaboracionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboPropuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPropuestasActionPerformed
        cargarDatos();
    }//GEN-LAST:event_comboPropuestasActionPerformed
    
    private void cargarCombo(){
        comboPropuestas.removeAllItems();
        comboColaboradores.removeAllItems();
        for (String tit : controlador.getTituloPropuestas()) {
            comboPropuestas.addItem(tit);
        }

        for(String nick : controlador.getNickColaboradores()){
            comboColaboradores.addItem(nick);
        }
    }
    
    private void cargarLista(){
        DefaultListModel dlm = new DefaultListModel<>();
        dlm.clear();
        for(TipoRetorno tr : TipoRetorno.values()){
            dlm.addElement(tr.toString());
        }
        listaTipoRet.setModel(dlm);
    }
    
    private void cargarDatos(){
        String propuestaSeleccionada = (String) comboPropuestas.getSelectedItem();
        if(propuestaSeleccionada != null){
        String titulo = propuestaSeleccionada.split(" - ")[0];
        DTPropuesta p = controlador.getDTPropuesta(titulo);
        jlTitulo.setText(p.getTitulo());
        jtaDesc.setText(p.getDescripcion());
        jlLugar.setText(p.getLugar());
        jlFecha.setText(p.getFechaPrevista().toString());
        jlPrecio.setText(String.valueOf(p.getPrecioEntrada()));
        jlMontoNec.setText(String.valueOf(p.getMontoNecesario()));
        jlMontoRec.setText(String.valueOf(p.getMontoRecaudado()));
        jlProponente.setText(p.getProponente());
        jlEstadoActual.setText(p.getEstadoActual().toString());
        // Agregar aca el nombre del proponente **********************************+++
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> comboColaboradores;
    private javax.swing.JComboBox<String> comboPropuestas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlEstadoActual;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlLugar;
    private javax.swing.JLabel jlMontoColab;
    private javax.swing.JLabel jlMontoNec;
    private javax.swing.JLabel jlMontoRec;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JLabel jlProponente;
    private javax.swing.JLabel jlPropuesta;
    private javax.swing.JLabel jlTipoRet;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtMontoColaboracion;
    private javax.swing.JTextPane jtaDesc;
    private javax.swing.JList<String> listaTipoRet;
    // End of variables declaration//GEN-END:variables
}
